Add virtual destructors for WindowManagerInterface and ViewportProjectionFinder (#356)
To fix the following warnings (converted to errors by compile options):
error: destructor called on non-final 'MockProjectionFinder' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
error: destructor called on non-final 'MockWindowManagerInterface' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]